language: python
python:
    - "2.7"
virtualenv:
  system_site_packages: true
# Enable container-based infrastructure
sudo: false
# install dependencies
 addons:
   apt:
     packages:
       - python-scipy
       - python-vtk
install:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - "pip install ."
  # Use --pre to get krypy alpha
  - "pip install -r requirements.txt"
  - pip install coveralls
# command to run tests
script:
  - nosetests --with-coverage --cover-package=pynosh
after_success:
  - coveralls
