language: python

python:
    - "2.7"

virtualenv:
  system_site_packages: true

# Enable container-based infrastructure
sudo: false

# install dependencies
addons:
  apt:
    packages:
      - python-scipy
      - python-vtk

install:
  - pip install -r requirements.txt
  - pip install coveralls
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# command to run tests
script:
  # cd into test directory to make sure we're using the pip-installed
  # pynosh.
  - cd tests
  - nosetests --with-coverage --cover-package=pynosh

after_success:
  - coveralls
